[package]
name = "rotire"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.11.6"
flate2 = "1.1.0"
log = "0.4.26"
tar = "0.4.44"

[dev-dependencies]
tempfile = "3.20.0"
